export const posts = [
  {
    postId: 1,
    clientId: 1,
    jobTitle: "Associate Professor",
    jobType: "Fixed",
    budget: 549,
    hourlyRate: 24.9,
    description: "Teacher at an elementary school",
    status: "Pending",
    isJobAccepted: false,
    createdAt: "6/24/2025",
  },
  {
    postId: 2,
    clientId: 2,
    jobTitle: "Staff Accountant IV",
    jobType: "Hourly",
    budget: 154,
    hourlyRate: 33.1,
    description: "Chef at a restaurant",
    status: "Accepted",
    isJobAccepted: false,
    createdAt: "12/7/2024",
  },
  {
    postId: 3,
    clientId: 3,
    jobTitle: "Senior Financial Analyst",
    jobType: "Fixed",
    budget: 731,
    hourlyRate: 29.6,
    description: "Software engineer at a tech company",
    status: "Pending",
    isJobAccepted: false,
    createdAt: "5/21/2025",
  },
  {
    postId: 4,
    clientId: 4,
    jobTitle: "Database Administrator IV",
    jobType: "Hourly",
    budget: 802,
    hourlyRate: 35.2,
    description: "Teacher at an elementary school",
    status: "Accepted",
    isJobAccepted: true,
    createdAt: "11/2/2025",
  },
  {
    postId: 5,
    clientId: 5,
    jobTitle: "Recruiting Manager",
    jobType: "Fixed",
    budget: 685,
    hourlyRate: 38.0,
    description: "Chef at a restaurant",
    status: "Pending",
    isJobAccepted: true,
    createdAt: "10/12/2025",
  },
  {
    postId: 6,
    clientId: 6,
    jobTitle: "Structural Engineer",
    jobType: "Fixed",
    budget: 386,
    hourlyRate: 28.3,
    description: "Marketing manager for a retail chain",
    status: "Pending",
    isJobAccepted: false,
    createdAt: "4/22/2025",
  },
  {
    postId: 7,
    clientId: 7,
    jobTitle: "Research Nurse",
    jobType: "Fixed",
    budget: 419,
    hourlyRate: 29.8,
    description: "Chef at a restaurant",
    status: "Pending",
    isJobAccepted: false,
    createdAt: "6/22/2025",
  },
  {
    postId: 8,
    clientId: 8,
    jobTitle: "Automation Specialist I",
    jobType: "Hourly",
    budget: 986,
    hourlyRate: 33.4,
    description: "Chef at a restaurant",
    status: "Accepted",
    isJobAccepted: false,
    createdAt: "1/8/2025",
  },
  {
    postId: 9,
    clientId: 9,
    jobTitle: "Civil Engineer",
    jobType: "Hourly",
    budget: 279,
    hourlyRate: 16.5,
    description: "Marketing manager for a retail chain",
    status: "Rejected",
    isJobAccepted: true,
    createdAt: "4/18/2025",
  },
  {
    postId: 10,
    clientId: 10,
    jobTitle: "Staff Accountant II",
    jobType: "Hourly",
    budget: 365,
    hourlyRate: 21.6,
    description: "Software engineer at a tech company",
    status: "Pending",
    isJobAccepted: true,
    createdAt: "4/18/2025",
  },
];
