import {
  Home,
  Login,
  Register,
  About,
  TermsandPolicies,
  Onboarding,
  Profile,
  Pending,
  UsersControlPanel,
  TagsControlPanel,
  Wall,
  NewPost,
  Chat,
  Proposals,
} from "@/pages";

export const APP_ROUTES = [
  { path: "/", element: <Home /> },
  { path: "login", element: <Login /> },
  { path: "register", element: <Register /> },
  { path: "about", element: <About /> },
  { path: "terms-and-policies", element: <TermsandPolicies /> },
  { path: "onboarding", element: <Onboarding /> },
  { path: "profile", element: <Profile /> },
  { path: "profile/:profileQuery", element: <Profile /> },
  { path: "pending", element: <Pending /> },
  { path: "users-control-panel", element: <UsersControlPanel /> },
  { path: "tags-control-panel", element: <TagsControlPanel /> },
  { path: "wall", element: <Wall /> },
  { path: "newpost", element: <NewPost /> },
  { path: "chat", element: <Chat /> },
  { path: "chat/:postId", element: <Chat /> },
  { path: "proposals", element: <Proposals /> },
];
