export const users = [
  {
    userId: 1,
    role: "Admin",
    firstName: "Tabb",
    lastName: "Price",
    email: "tprice0@t-online.de",
    title: "Junior Executive",
    country: "Afghanistan",
    bio: "Hardworking individual with a passion for learning",
    createdAt: "2/19/2025",
  },
  {
    userId: 2,
    role: "Client",
    firstName: "Brnaby",
    lastName: "Gloves",
    email: "bgloves1@nifty.com",
    title: "Recruiter",
    country: "Afghanistan",
    bio: "Detail-oriented team player with strong communication abilities",
    createdAt: "1/3/2025",
  },
  {
    userId: 3,
    role: "Client",
    firstName: "Denna",
    lastName: "Faier",
    email: "dfaier2@google.ca",
    title: "Nurse",
    country: "Afghanistan",
    bio: "Creative thinker with excellent problem-solving skills",
    createdAt: "4/3/2025",
  },
  {
    userId: 4,
    role: "Freelancer",
    firstName: "Jo ann",
    lastName: "Rassell",
    email: "jrassell3@google.pl",
    title: "Tax Accountant",
    country: "Afghanistan",
    bio: "Hardworking individual with a passion for learning",
    createdAt: "9/8/2025",
  },
  {
    userId: 5,
    role: "Client",
    firstName: "Joey",
    lastName: "Bernardes",
    email: "jbernardes4@time.com",
    title: "Associate Professor",
    country: "Afghanistan",
    bio: "Hardworking individual with a passion for learning",
    createdAt: "4/25/2025",
  },
  {
    userId: 6,
    role: "Freelancer",
    firstName: "Conrado",
    lastName: "Pigeon",
    email: "cpigeon5@wordpress.com",
    title: "Director of Sales",
    country: "Afghanistan",
    bio: "Creative thinker with excellent problem-solving skills",
    createdAt: "9/9/2025",
  },
  {
    userId: 7,
    role: "Client",
    firstName: "Timoteo",
    lastName: "Sargint",
    email: "tsargint6@msu.edu",
    title: "Software Consultant",
    country: "Afghanistan",
    bio: "Hardworking individual with a passion for learning",
    createdAt: "3/6/2025",
  },
  {
    userId: 8,
    role: "Admin",
    firstName: "Gerrilee",
    lastName: "Ulyatt",
    email: "gulyatt7@shutterfly.com",
    title: "Account Coordinator",
    country: "Afghanistan",
    bio: "Hardworking individual with a passion for learning",
    createdAt: "10/10/2025",
  },
  {
    userId: 9,
    role: "Freelancer",
    firstName: "Shelby",
    lastName: "Barbe",
    email: "sbarbe8@cloudflare.com",
    title: "Marketing Manager",
    country: "Afghanistan",
    bio: "Creative thinker with excellent problem-solving skills",
    createdAt: "6/8/2025",
  },
  {
    userId: 10,
    role: "Freelancer",
    firstName: "Esther",
    lastName: "Fauning",
    email: "efauning9@tripadvisor.com",
    title: "Clinical Specialist",
    country: "Afghanistan",
    bio: "Creative thinker with excellent problem-solving skills",
    createdAt: "2/9/2025",
  },
];
